name: buckly-ms
services:

  postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_DB: buckly-dev-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: External000
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - network

  gateway:
    container_name: gateway
    build: 
      context: .
      dockerfile: gateway/Dockerfile
    env_file:
      - gateway/.env
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/certs
    networks:
      - network
  
  database-service:
    container_name: database-service
    build:
      context: .
      dockerfile: services/database-service/Dockerfile
    env_file:
      - services/database-service/.env
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    volumes:
      - ./certs:/certs
    networks:
      - network
networks:
  network:
    driver: bridge

volumes:
  postgres_data: