// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/bucket-list/dto/bucket-list-dto.proto

package bucket_list_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketListItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityTagId      int64                  `protobuf:"varint,3,opt,name=activity_tag_id,json=activityTagId,proto3" json:"activity_tag_id,omitempty"`
	CountryId          int64                  `protobuf:"varint,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	StateId            int64                  `protobuf:"varint,5,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CityId             int64                  `protobuf:"varint,6,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	TimeframeStartDate string                 `protobuf:"bytes,7,opt,name=timeframe_start_date,json=timeframeStartDate,proto3" json:"timeframe_start_date,omitempty"`
	TimeframeEndDate   string                 `protobuf:"bytes,8,opt,name=timeframe_end_date,json=timeframeEndDate,proto3" json:"timeframe_end_date,omitempty"`
	Note               string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	IsPublic           bool                   `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status             string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	InsertTs           *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=insert_ts,json=insertTs,proto3" json:"insert_ts,omitempty"`
	ModifiedTs         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=modified_ts,json=modifiedTs,proto3" json:"modified_ts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BucketListItem) Reset() {
	*x = BucketListItem{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketListItem) ProtoMessage() {}

func (x *BucketListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketListItem.ProtoReflect.Descriptor instead.
func (*BucketListItem) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{0}
}

func (x *BucketListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BucketListItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BucketListItem) GetActivityTagId() int64 {
	if x != nil {
		return x.ActivityTagId
	}
	return 0
}

func (x *BucketListItem) GetCountryId() int64 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *BucketListItem) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *BucketListItem) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *BucketListItem) GetTimeframeStartDate() string {
	if x != nil {
		return x.TimeframeStartDate
	}
	return ""
}

func (x *BucketListItem) GetTimeframeEndDate() string {
	if x != nil {
		return x.TimeframeEndDate
	}
	return ""
}

func (x *BucketListItem) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *BucketListItem) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *BucketListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BucketListItem) GetInsertTs() *timestamppb.Timestamp {
	if x != nil {
		return x.InsertTs
	}
	return nil
}

func (x *BucketListItem) GetModifiedTs() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTs
	}
	return nil
}

type CreateBucketListItemRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityTagId      int64                  `protobuf:"varint,2,opt,name=activity_tag_id,json=activityTagId,proto3" json:"activity_tag_id,omitempty"`
	CountryId          int64                  `protobuf:"varint,3,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	StateId            int64                  `protobuf:"varint,4,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CityId             int64                  `protobuf:"varint,5,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	TimeframeStartDate string                 `protobuf:"bytes,6,opt,name=timeframe_start_date,json=timeframeStartDate,proto3" json:"timeframe_start_date,omitempty"`
	TimeframeEndDate   string                 `protobuf:"bytes,7,opt,name=timeframe_end_date,json=timeframeEndDate,proto3" json:"timeframe_end_date,omitempty"`
	Note               string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	IsPublic           bool                   `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateBucketListItemRequest) Reset() {
	*x = CreateBucketListItemRequest{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketListItemRequest) ProtoMessage() {}

func (x *CreateBucketListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketListItemRequest.ProtoReflect.Descriptor instead.
func (*CreateBucketListItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBucketListItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateBucketListItemRequest) GetActivityTagId() int64 {
	if x != nil {
		return x.ActivityTagId
	}
	return 0
}

func (x *CreateBucketListItemRequest) GetCountryId() int64 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *CreateBucketListItemRequest) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *CreateBucketListItemRequest) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *CreateBucketListItemRequest) GetTimeframeStartDate() string {
	if x != nil {
		return x.TimeframeStartDate
	}
	return ""
}

func (x *CreateBucketListItemRequest) GetTimeframeEndDate() string {
	if x != nil {
		return x.TimeframeEndDate
	}
	return ""
}

func (x *CreateBucketListItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateBucketListItemRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateBucketListItemResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketListItem *BucketListItem        `protobuf:"bytes,1,opt,name=bucket_list_item,json=bucketListItem,proto3" json:"bucket_list_item,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBucketListItemResponse) Reset() {
	*x = CreateBucketListItemResponse{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBucketListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBucketListItemResponse) ProtoMessage() {}

func (x *CreateBucketListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBucketListItemResponse.ProtoReflect.Descriptor instead.
func (*CreateBucketListItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBucketListItemResponse) GetBucketListItem() *BucketListItem {
	if x != nil {
		return x.BucketListItem
	}
	return nil
}

type GetBucketListItemsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketListItemsByUserIdRequest) Reset() {
	*x = GetBucketListItemsByUserIdRequest{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketListItemsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketListItemsByUserIdRequest) ProtoMessage() {}

func (x *GetBucketListItemsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketListItemsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetBucketListItemsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{3}
}

func (x *GetBucketListItemsByUserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBucketListItemsByUserIdResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BucketListItems []*BucketListItem      `protobuf:"bytes,1,rep,name=bucket_list_items,json=bucketListItems,proto3" json:"bucket_list_items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBucketListItemsByUserIdResponse) Reset() {
	*x = GetBucketListItemsByUserIdResponse{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketListItemsByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketListItemsByUserIdResponse) ProtoMessage() {}

func (x *GetBucketListItemsByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketListItemsByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetBucketListItemsByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{4}
}

func (x *GetBucketListItemsByUserIdResponse) GetBucketListItems() []*BucketListItem {
	if x != nil {
		return x.BucketListItems
	}
	return nil
}

type GetBucketListItemByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketListItemByIdRequest) Reset() {
	*x = GetBucketListItemByIdRequest{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketListItemByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketListItemByIdRequest) ProtoMessage() {}

func (x *GetBucketListItemByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketListItemByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBucketListItemByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{5}
}

func (x *GetBucketListItemByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBucketListItemByIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBucketListItemByIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketListItem *BucketListItem        `protobuf:"bytes,2,opt,name=bucket_list_item,json=bucketListItem,proto3" json:"bucket_list_item,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBucketListItemByIdResponse) Reset() {
	*x = GetBucketListItemByIdResponse{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketListItemByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketListItemByIdResponse) ProtoMessage() {}

func (x *GetBucketListItemByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketListItemByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBucketListItemByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{6}
}

func (x *GetBucketListItemByIdResponse) GetBucketListItem() *BucketListItem {
	if x != nil {
		return x.BucketListItem
	}
	return nil
}

type UpdateBucketListItemRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityTagId      int64                  `protobuf:"varint,3,opt,name=activity_tag_id,json=activityTagId,proto3" json:"activity_tag_id,omitempty"`
	CountryId          int64                  `protobuf:"varint,4,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	StateId            int64                  `protobuf:"varint,5,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CityId             int64                  `protobuf:"varint,6,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	TimeframeStartDate string                 `protobuf:"bytes,7,opt,name=timeframe_start_date,json=timeframeStartDate,proto3" json:"timeframe_start_date,omitempty"`
	TimeframeEndDate   string                 `protobuf:"bytes,8,opt,name=timeframe_end_date,json=timeframeEndDate,proto3" json:"timeframe_end_date,omitempty"`
	Note               string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	IsPublic           bool                   `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateBucketListItemRequest) Reset() {
	*x = UpdateBucketListItemRequest{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBucketListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBucketListItemRequest) ProtoMessage() {}

func (x *UpdateBucketListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBucketListItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateBucketListItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBucketListItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBucketListItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBucketListItemRequest) GetActivityTagId() int64 {
	if x != nil {
		return x.ActivityTagId
	}
	return 0
}

func (x *UpdateBucketListItemRequest) GetCountryId() int64 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *UpdateBucketListItemRequest) GetStateId() int64 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *UpdateBucketListItemRequest) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *UpdateBucketListItemRequest) GetTimeframeStartDate() string {
	if x != nil {
		return x.TimeframeStartDate
	}
	return ""
}

func (x *UpdateBucketListItemRequest) GetTimeframeEndDate() string {
	if x != nil {
		return x.TimeframeEndDate
	}
	return ""
}

func (x *UpdateBucketListItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateBucketListItemRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type UpdateBucketListItemResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketListItem *BucketListItem        `protobuf:"bytes,1,opt,name=bucket_list_item,json=bucketListItem,proto3" json:"bucket_list_item,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateBucketListItemResponse) Reset() {
	*x = UpdateBucketListItemResponse{}
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBucketListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBucketListItemResponse) ProtoMessage() {}

func (x *UpdateBucketListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBucketListItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateBucketListItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBucketListItemResponse) GetBucketListItem() *BucketListItem {
	if x != nil {
		return x.BucketListItem
	}
	return nil
}

var File_proto_bucket_list_dto_bucket_list_dto_proto protoreflect.FileDescriptor

const file_proto_bucket_list_dto_bucket_list_dto_proto_rawDesc = "" +
	"\n" +
	"+proto/bucket-list/dto/bucket-list-dto.proto\x12\vbucket_list\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x03\n" +
	"\x0eBucketListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0factivity_tag_id\x18\x03 \x01(\x03R\ractivityTagId\x12\x1d\n" +
	"\n" +
	"country_id\x18\x04 \x01(\x03R\tcountryId\x12\x19\n" +
	"\bstate_id\x18\x05 \x01(\x03R\astateId\x12\x17\n" +
	"\acity_id\x18\x06 \x01(\x03R\x06cityId\x120\n" +
	"\x14timeframe_start_date\x18\a \x01(\tR\x12timeframeStartDate\x12,\n" +
	"\x12timeframe_end_date\x18\b \x01(\tR\x10timeframeEndDate\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x12\x1b\n" +
	"\tis_public\x18\n" +
	" \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x127\n" +
	"\tinsert_ts\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\binsertTs\x12;\n" +
	"\vmodified_ts\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedTs\"\xc2\x02\n" +
	"\x1bCreateBucketListItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0factivity_tag_id\x18\x02 \x01(\x03R\ractivityTagId\x12\x1d\n" +
	"\n" +
	"country_id\x18\x03 \x01(\x03R\tcountryId\x12\x19\n" +
	"\bstate_id\x18\x04 \x01(\x03R\astateId\x12\x17\n" +
	"\acity_id\x18\x05 \x01(\x03R\x06cityId\x120\n" +
	"\x14timeframe_start_date\x18\x06 \x01(\tR\x12timeframeStartDate\x12,\n" +
	"\x12timeframe_end_date\x18\a \x01(\tR\x10timeframeEndDate\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x1b\n" +
	"\tis_public\x18\t \x01(\bR\bisPublic\"e\n" +
	"\x1cCreateBucketListItemResponse\x12E\n" +
	"\x10bucket_list_item\x18\x01 \x01(\v2\x1b.bucket_list.BucketListItemR\x0ebucketListItem\"<\n" +
	"!GetBucketListItemsByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"m\n" +
	"\"GetBucketListItemsByUserIdResponse\x12G\n" +
	"\x11bucket_list_items\x18\x01 \x03(\v2\x1b.bucket_list.BucketListItemR\x0fbucketListItems\"G\n" +
	"\x1cGetBucketListItemByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"f\n" +
	"\x1dGetBucketListItemByIdResponse\x12E\n" +
	"\x10bucket_list_item\x18\x02 \x01(\v2\x1b.bucket_list.BucketListItemR\x0ebucketListItem\"\xd2\x02\n" +
	"\x1bUpdateBucketListItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0factivity_tag_id\x18\x03 \x01(\x03R\ractivityTagId\x12\x1d\n" +
	"\n" +
	"country_id\x18\x04 \x01(\x03R\tcountryId\x12\x19\n" +
	"\bstate_id\x18\x05 \x01(\x03R\astateId\x12\x17\n" +
	"\acity_id\x18\x06 \x01(\x03R\x06cityId\x120\n" +
	"\x14timeframe_start_date\x18\a \x01(\tR\x12timeframeStartDate\x12,\n" +
	"\x12timeframe_end_date\x18\b \x01(\tR\x10timeframeEndDate\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x12\x1b\n" +
	"\tis_public\x18\n" +
	" \x01(\bR\bisPublic\"e\n" +
	"\x1cUpdateBucketListItemResponse\x12E\n" +
	"\x10bucket_list_item\x18\x01 \x01(\v2\x1b.bucket_list.BucketListItemR\x0ebucketListItemB\x17Z\x15proto/bucket-list-genb\x06proto3"

var (
	file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescOnce sync.Once
	file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescData []byte
)

func file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescGZIP() []byte {
	file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescOnce.Do(func() {
		file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bucket_list_dto_bucket_list_dto_proto_rawDesc), len(file_proto_bucket_list_dto_bucket_list_dto_proto_rawDesc)))
	})
	return file_proto_bucket_list_dto_bucket_list_dto_proto_rawDescData
}

var file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_bucket_list_dto_bucket_list_dto_proto_goTypes = []any{
	(*BucketListItem)(nil),                     // 0: bucket_list.BucketListItem
	(*CreateBucketListItemRequest)(nil),        // 1: bucket_list.CreateBucketListItemRequest
	(*CreateBucketListItemResponse)(nil),       // 2: bucket_list.CreateBucketListItemResponse
	(*GetBucketListItemsByUserIdRequest)(nil),  // 3: bucket_list.GetBucketListItemsByUserIdRequest
	(*GetBucketListItemsByUserIdResponse)(nil), // 4: bucket_list.GetBucketListItemsByUserIdResponse
	(*GetBucketListItemByIdRequest)(nil),       // 5: bucket_list.GetBucketListItemByIdRequest
	(*GetBucketListItemByIdResponse)(nil),      // 6: bucket_list.GetBucketListItemByIdResponse
	(*UpdateBucketListItemRequest)(nil),        // 7: bucket_list.UpdateBucketListItemRequest
	(*UpdateBucketListItemResponse)(nil),       // 8: bucket_list.UpdateBucketListItemResponse
	(*timestamppb.Timestamp)(nil),              // 9: google.protobuf.Timestamp
}
var file_proto_bucket_list_dto_bucket_list_dto_proto_depIdxs = []int32{
	9, // 0: bucket_list.BucketListItem.insert_ts:type_name -> google.protobuf.Timestamp
	9, // 1: bucket_list.BucketListItem.modified_ts:type_name -> google.protobuf.Timestamp
	0, // 2: bucket_list.CreateBucketListItemResponse.bucket_list_item:type_name -> bucket_list.BucketListItem
	0, // 3: bucket_list.GetBucketListItemsByUserIdResponse.bucket_list_items:type_name -> bucket_list.BucketListItem
	0, // 4: bucket_list.GetBucketListItemByIdResponse.bucket_list_item:type_name -> bucket_list.BucketListItem
	0, // 5: bucket_list.UpdateBucketListItemResponse.bucket_list_item:type_name -> bucket_list.BucketListItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_bucket_list_dto_bucket_list_dto_proto_init() }
func file_proto_bucket_list_dto_bucket_list_dto_proto_init() {
	if File_proto_bucket_list_dto_bucket_list_dto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bucket_list_dto_bucket_list_dto_proto_rawDesc), len(file_proto_bucket_list_dto_bucket_list_dto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bucket_list_dto_bucket_list_dto_proto_goTypes,
		DependencyIndexes: file_proto_bucket_list_dto_bucket_list_dto_proto_depIdxs,
		MessageInfos:      file_proto_bucket_list_dto_bucket_list_dto_proto_msgTypes,
	}.Build()
	File_proto_bucket_list_dto_bucket_list_dto_proto = out.File
	file_proto_bucket_list_dto_bucket_list_dto_proto_goTypes = nil
	file_proto_bucket_list_dto_bucket_list_dto_proto_depIdxs = nil
}
