// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/bucket-list/bucket-list-service.proto

package bucket_list_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BucketListService_CreateBucketListItem_FullMethodName         = "/bucket_list.BucketListService/CreateBucketListItem"
	BucketListService_GetBucketListItemsByUserId_FullMethodName   = "/bucket_list.BucketListService/GetBucketListItemsByUserId"
	BucketListService_GetBucketListItemById_FullMethodName        = "/bucket_list.BucketListService/GetBucketListItemById"
	BucketListService_UpdateBucketListItem_FullMethodName         = "/bucket_list.BucketListService/UpdateBucketListItem"
	BucketListService_DeleteBucketListItem_FullMethodName         = "/bucket_list.BucketListService/DeleteBucketListItem"
	BucketListService_FindMatchesForBucketListItem_FullMethodName = "/bucket_list.BucketListService/FindMatchesForBucketListItem"
)

// BucketListServiceClient is the client API for BucketListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BucketListServiceClient interface {
	CreateBucketListItem(ctx context.Context, in *CreateBucketListItemRequest, opts ...grpc.CallOption) (*CreateBucketListItemResponse, error)
	GetBucketListItemsByUserId(ctx context.Context, in *GetBucketListItemsByUserIdRequest, opts ...grpc.CallOption) (*GetBucketListItemsByUserIdResponse, error)
	GetBucketListItemById(ctx context.Context, in *GetBucketListItemByIdRequest, opts ...grpc.CallOption) (*GetBucketListItemByIdResponse, error)
	UpdateBucketListItem(ctx context.Context, in *UpdateBucketListItemRequest, opts ...grpc.CallOption) (*UpdateBucketListItemResponse, error)
	DeleteBucketListItem(ctx context.Context, in *DeleteBucketListItemRequest, opts ...grpc.CallOption) (*DeleteBucketListItemResponse, error)
	FindMatchesForBucketListItem(ctx context.Context, in *FindMatchesForBucketListItemRequest, opts ...grpc.CallOption) (*FindMatchesForBucketListItemResponse, error)
}

type bucketListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBucketListServiceClient(cc grpc.ClientConnInterface) BucketListServiceClient {
	return &bucketListServiceClient{cc}
}

func (c *bucketListServiceClient) CreateBucketListItem(ctx context.Context, in *CreateBucketListItemRequest, opts ...grpc.CallOption) (*CreateBucketListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketListItemResponse)
	err := c.cc.Invoke(ctx, BucketListService_CreateBucketListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketListServiceClient) GetBucketListItemsByUserId(ctx context.Context, in *GetBucketListItemsByUserIdRequest, opts ...grpc.CallOption) (*GetBucketListItemsByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketListItemsByUserIdResponse)
	err := c.cc.Invoke(ctx, BucketListService_GetBucketListItemsByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketListServiceClient) GetBucketListItemById(ctx context.Context, in *GetBucketListItemByIdRequest, opts ...grpc.CallOption) (*GetBucketListItemByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketListItemByIdResponse)
	err := c.cc.Invoke(ctx, BucketListService_GetBucketListItemById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketListServiceClient) UpdateBucketListItem(ctx context.Context, in *UpdateBucketListItemRequest, opts ...grpc.CallOption) (*UpdateBucketListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBucketListItemResponse)
	err := c.cc.Invoke(ctx, BucketListService_UpdateBucketListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketListServiceClient) DeleteBucketListItem(ctx context.Context, in *DeleteBucketListItemRequest, opts ...grpc.CallOption) (*DeleteBucketListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBucketListItemResponse)
	err := c.cc.Invoke(ctx, BucketListService_DeleteBucketListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketListServiceClient) FindMatchesForBucketListItem(ctx context.Context, in *FindMatchesForBucketListItemRequest, opts ...grpc.CallOption) (*FindMatchesForBucketListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindMatchesForBucketListItemResponse)
	err := c.cc.Invoke(ctx, BucketListService_FindMatchesForBucketListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BucketListServiceServer is the server API for BucketListService service.
// All implementations must embed UnimplementedBucketListServiceServer
// for forward compatibility.
type BucketListServiceServer interface {
	CreateBucketListItem(context.Context, *CreateBucketListItemRequest) (*CreateBucketListItemResponse, error)
	GetBucketListItemsByUserId(context.Context, *GetBucketListItemsByUserIdRequest) (*GetBucketListItemsByUserIdResponse, error)
	GetBucketListItemById(context.Context, *GetBucketListItemByIdRequest) (*GetBucketListItemByIdResponse, error)
	UpdateBucketListItem(context.Context, *UpdateBucketListItemRequest) (*UpdateBucketListItemResponse, error)
	DeleteBucketListItem(context.Context, *DeleteBucketListItemRequest) (*DeleteBucketListItemResponse, error)
	FindMatchesForBucketListItem(context.Context, *FindMatchesForBucketListItemRequest) (*FindMatchesForBucketListItemResponse, error)
	mustEmbedUnimplementedBucketListServiceServer()
}

// UnimplementedBucketListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBucketListServiceServer struct{}

func (UnimplementedBucketListServiceServer) CreateBucketListItem(context.Context, *CreateBucketListItemRequest) (*CreateBucketListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucketListItem not implemented")
}
func (UnimplementedBucketListServiceServer) GetBucketListItemsByUserId(context.Context, *GetBucketListItemsByUserIdRequest) (*GetBucketListItemsByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketListItemsByUserId not implemented")
}
func (UnimplementedBucketListServiceServer) GetBucketListItemById(context.Context, *GetBucketListItemByIdRequest) (*GetBucketListItemByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketListItemById not implemented")
}
func (UnimplementedBucketListServiceServer) UpdateBucketListItem(context.Context, *UpdateBucketListItemRequest) (*UpdateBucketListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBucketListItem not implemented")
}
func (UnimplementedBucketListServiceServer) DeleteBucketListItem(context.Context, *DeleteBucketListItemRequest) (*DeleteBucketListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucketListItem not implemented")
}
func (UnimplementedBucketListServiceServer) FindMatchesForBucketListItem(context.Context, *FindMatchesForBucketListItemRequest) (*FindMatchesForBucketListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMatchesForBucketListItem not implemented")
}
func (UnimplementedBucketListServiceServer) mustEmbedUnimplementedBucketListServiceServer() {}
func (UnimplementedBucketListServiceServer) testEmbeddedByValue()                           {}

// UnsafeBucketListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BucketListServiceServer will
// result in compilation errors.
type UnsafeBucketListServiceServer interface {
	mustEmbedUnimplementedBucketListServiceServer()
}

func RegisterBucketListServiceServer(s grpc.ServiceRegistrar, srv BucketListServiceServer) {
	// If the following call panics, it indicates UnimplementedBucketListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BucketListService_ServiceDesc, srv)
}

func _BucketListService_CreateBucketListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).CreateBucketListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_CreateBucketListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).CreateBucketListItem(ctx, req.(*CreateBucketListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BucketListService_GetBucketListItemsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketListItemsByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).GetBucketListItemsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_GetBucketListItemsByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).GetBucketListItemsByUserId(ctx, req.(*GetBucketListItemsByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BucketListService_GetBucketListItemById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketListItemByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).GetBucketListItemById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_GetBucketListItemById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).GetBucketListItemById(ctx, req.(*GetBucketListItemByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BucketListService_UpdateBucketListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBucketListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).UpdateBucketListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_UpdateBucketListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).UpdateBucketListItem(ctx, req.(*UpdateBucketListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BucketListService_DeleteBucketListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).DeleteBucketListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_DeleteBucketListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).DeleteBucketListItem(ctx, req.(*DeleteBucketListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BucketListService_FindMatchesForBucketListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMatchesForBucketListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).FindMatchesForBucketListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_FindMatchesForBucketListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).FindMatchesForBucketListItem(ctx, req.(*FindMatchesForBucketListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BucketListService_ServiceDesc is the grpc.ServiceDesc for BucketListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BucketListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bucket_list.BucketListService",
	HandlerType: (*BucketListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucketListItem",
			Handler:    _BucketListService_CreateBucketListItem_Handler,
		},
		{
			MethodName: "GetBucketListItemsByUserId",
			Handler:    _BucketListService_GetBucketListItemsByUserId_Handler,
		},
		{
			MethodName: "GetBucketListItemById",
			Handler:    _BucketListService_GetBucketListItemById_Handler,
		},
		{
			MethodName: "UpdateBucketListItem",
			Handler:    _BucketListService_UpdateBucketListItem_Handler,
		},
		{
			MethodName: "DeleteBucketListItem",
			Handler:    _BucketListService_DeleteBucketListItem_Handler,
		},
		{
			MethodName: "FindMatchesForBucketListItem",
			Handler:    _BucketListService_FindMatchesForBucketListItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bucket-list/bucket-list-service.proto",
}
