// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/bucket-list/bucket-list-service.proto

package bucket_list_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BucketListService_CreateBucketListItem_FullMethodName = "/bucket_list.BucketListService/CreateBucketListItem"
)

// BucketListServiceClient is the client API for BucketListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BucketListServiceClient interface {
	CreateBucketListItem(ctx context.Context, in *CreateBucketListItemRequest, opts ...grpc.CallOption) (*CreateBucketListItemResponse, error)
}

type bucketListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBucketListServiceClient(cc grpc.ClientConnInterface) BucketListServiceClient {
	return &bucketListServiceClient{cc}
}

func (c *bucketListServiceClient) CreateBucketListItem(ctx context.Context, in *CreateBucketListItemRequest, opts ...grpc.CallOption) (*CreateBucketListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketListItemResponse)
	err := c.cc.Invoke(ctx, BucketListService_CreateBucketListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BucketListServiceServer is the server API for BucketListService service.
// All implementations must embed UnimplementedBucketListServiceServer
// for forward compatibility.
type BucketListServiceServer interface {
	CreateBucketListItem(context.Context, *CreateBucketListItemRequest) (*CreateBucketListItemResponse, error)
	mustEmbedUnimplementedBucketListServiceServer()
}

// UnimplementedBucketListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBucketListServiceServer struct{}

func (UnimplementedBucketListServiceServer) CreateBucketListItem(context.Context, *CreateBucketListItemRequest) (*CreateBucketListItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucketListItem not implemented")
}
func (UnimplementedBucketListServiceServer) mustEmbedUnimplementedBucketListServiceServer() {}
func (UnimplementedBucketListServiceServer) testEmbeddedByValue()                           {}

// UnsafeBucketListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BucketListServiceServer will
// result in compilation errors.
type UnsafeBucketListServiceServer interface {
	mustEmbedUnimplementedBucketListServiceServer()
}

func RegisterBucketListServiceServer(s grpc.ServiceRegistrar, srv BucketListServiceServer) {
	// If the following call panics, it indicates UnimplementedBucketListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BucketListService_ServiceDesc, srv)
}

func _BucketListService_CreateBucketListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketListServiceServer).CreateBucketListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BucketListService_CreateBucketListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketListServiceServer).CreateBucketListItem(ctx, req.(*CreateBucketListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BucketListService_ServiceDesc is the grpc.ServiceDesc for BucketListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BucketListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bucket_list.BucketListService",
	HandlerType: (*BucketListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucketListItem",
			Handler:    _BucketListService_CreateBucketListItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bucket-list/bucket-list-service.proto",
}
