package database_service

const (
	SERVICE_NAME  = "SERVICE_NAME"
	GRPC_PORT     = "GRPC_PORT"
	DATABASE_URL  = "DATABASE_URL"
	ENVIRONMENT   = "ENVIRONMENT"
	MAX_POOL_SIZE = "MAX_POOL_SIZE"
	MIN_POOL_SIZE = "MIN_POOL_SIZE"
)
